---
- name: ARISTA CONFIGURATION VALIDATION
  gather_facts: False
  hosts: pynet-sw7
  tasks:
  - name: Check connectivity
    eos_facts:
      provider: "{{ creds_eapi }}"
  - name: Apply configuration
    eos_config:
      provider: "{{ creds_eapi }}"
      lines: "vlan {{ item }}"
    with_items: "{{ vlans_id }}"
  - name: Verify configuration applied
    eos_command:
      provider: "{{ creds_eapi }}"
      commands:
        - show vlan
    register: all_output
  - set_fact:
      all_vlan: "{{ all_output.stdout_lines[0].vlans }}"
  - name: Print All VLAN output
    debug:
      msg: "{{ all_vlan }}"
  - name: Only Print Vlan ID
    debug:
      msg:  "{{ item.key }}"
    with_dict: "{{ all_vlan }}"
