---
- name: IOS facts gathering
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - name: IOS facts
      ios_facts:
        provider: "{{ creds }}"
    - name: Serial-number
      debug:
        msg: "{{ ansible_net_serialnum }}"
