---
- name: NXOS VLAN configuration
  hosts: nxos
  tasks:
    - name: VLAN configuration
      nxos_vlan:
        provider: "{{ provider_nxapi }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"
    
