---
provider_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: cli
  validate_certs: no
provider_nxapi:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: nxapi
  validate_certs: no
int_ip:
  - interface: Ethernet2/1
    addr_v4: "{{ ipadd1_v4 }}"
    mask_v4: 24
    addr_v6: "{{ ipadd1_v6 }}"
    mask_v6: 64
  - interface: Ethernet2/2
    addr_v4: "{{ ipadd2_v4 }}"
    mask_v4: 24
    addr_v6: "{{ ipadd2_v6 }}"
    mask_v6: 64
  - interface: Ethernet2/3
    addr_v4: "{{ ipadd3_v4 }}"
    mask_v4: 24
    addr_v6: "{{ ipadd3_v6 }}"
    mask_v6: 64
  - interface: Ethernet2/4
    addr_v4: "{{ ipadd4_v4 }}"
    mask_v4: 24
    addr_v6: "{{ ipadd4_v6 }}"
    mask_v6: 64
